<?php
// SPDX-License-Identifier: GPL-3.0-or-later

return [
    'name'        => 'IIT Bot Filter',
    'description' => 'Adds a list-free burst/velocity signal to Mautic bot detection so email opens and clicks generated by cloud link-scanning security services (Defender SafeLinks, Mimecast, Proofpoint, Barracuda, etc.) are discarded. Decorates the core BotRatioHelper; no maintained IP or user-agent list required.',
    'version'     => '1.10.2',
    'author'      => 'IntellectIT',
    'routes' => [
        'public' => [
            'mautic_botfilter_honeypot' => [
                'path'       => '/bf/honeypot',
                'controller' => 'MauticPlugin\IntellectITBotFilterBundle\Controller\HoneypotController::hitAction',
            ],
        ],
        'main' => [
            'mautic_botfilter_index' => [
                'path'       => '/botfilter/{page}',
                'controller' => 'MauticPlugin\IntellectITBotFilterBundle\Controller\BotFilterController::indexAction',
            ],
            'mautic_botfilter_contact' => [
                'path'         => '/botfilter/contact/{leadId}/{page}',
                'controller'   => 'MauticPlugin\IntellectITBotFilterBundle\Controller\BotFilterController::contactAction',
                'requirements' => ['leadId' => '\d+'],
            ],
        ],
    ],
    'menu' => [
        'main' => [
            'mautic.botfilter.menu.index' => [
                'route'     => 'mautic_botfilter_index',
                'access'    => ['lead:leads:viewown', 'lead:leads:viewother'],
                'parent'    => 'mautic.core.channels',
                // Menu sorts by priority descending (higher = first). 90 is a mid-range value
                // so "Bot Filter" sits among other plugin entries under Channels rather than
                // being pinned to the top or bottom; adjust it if you need a different position.
                // Core/third-party Channels items (Emails, SMS, Social, etc.) have their own
                // fixed priorities, so the full submenu is not strictly alphabetical end-to-end.
                'priority'  => 90,
            ],
        ],
    ],
    'services' => [
        'integrations' => [
            'mautic.integration.intellectitbotfilter' => [
                'class'     => \MauticPlugin\IntellectITBotFilterBundle\Integration\IntellectITBotFilterIntegration::class,
                'arguments' => [
                    'event_dispatcher',
                    'mautic.helper.cache_storage',
                    'doctrine.orm.entity_manager',
                    'request_stack',
                    'router',
                    'translator',
                    'monolog.logger.mautic',
                    'mautic.helper.encryption',
                    'mautic.lead.model.lead',
                    'mautic.lead.model.company',
                    'mautic.helper.paths',
                    'mautic.core.model.notification',
                    'mautic.lead.model.field',
                    'mautic.plugin.model.integration_entity',
                    'mautic.lead.model.dnc',
                    'mautic.lead.field.fields_with_unique_identifier',
                ],
            ],
        ],
    ],
];
